<a href="https://colab.research.google.com/github/sautiw/Numerical-Methods/blob/main/Project4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math
import numpy as np

## **Gauss-Jordan Method**

Gauss-Jordan is an algorithm used in solving different systems of linear equations categorizing equations with both two and three unknowns. The algorithm relies on the fundamental row operations of matrices and arithmetic operations on rows that allow for finding the inverse of invertible matrices. A reduced-row echelon form is a form a matrix takes when evaluated using the Gauss-Jordan elimination algorithm. This allows for matrices to essentially be solved since they follow a set of rules that dictate when a matrix is in the Reduced-row echelon form. The procedure to perform the Gauss-Jordan Elimination is:
1.	Switch the rows so that rows with zeros are at the bottom.
2.	Move the largest leftmost entity to the top of the row.
3.	Change the top row to one by multiplying it by a scalar value.
4.	Add or subtract multiples of the top row to the other rows so that all other entries in the column containing the top row's leading entry are all zero.
5.	Repeat steps two to four to convert the subsequent leftmost matrix entry to one.
6.	Switch rows to ensure the leading entry of each row is to the right of the leading entry of the row above it.


Using the inverse of a matrix often helps in solving the systems of linear equations. The inverse is obtained using the “hstack” function contained in the NumPy library. The algorithm works best for linear equations that take the form Ax=b where there is a unique solution for the value of x. Such systems can also be solved using the library “scipy.linalg” which provides different functions to efficiently evaluate such equations.


In [ ]:
A = np.array([[6,15,1,2],[8,7,12,14],[2,7,8,10]])

Find Inverse of matrix for solution solving system further on.

In [ ]:
M = np.hstack([A])
print(M)

[[ 6 15  1  2]
 [ 8  7 12 14]
 [ 2  7  8 10]]


Function for Swapping rows

In [ ]:
def swapRows(matrix,row1,row2):
  newMatrix = []
  for i in range(len(matrix)):
    if i == row1:
      newMatrix.append(matrix[row2,:])
    elif i == row2:
      newMatrix.append(matrix[row1,:])
    else:
      newMatrix.append(matrix[i,:])
  return np.array(newMatrix)


In [ ]:

swapRows(A,0,1)

array([[ 8,  7, 12, 14],
       [ 6, 15,  1,  2],
       [ 2,  7,  8, 10]])

Function for adding rows

In [ ]:
def addRows(matrix,targetRow, modifierRow, value):
  newRow = matrix[targetRow,:]+value*matrix[modifierRow,:]
  newMatrix = []
  for i in range(len(matrix)):
    if i != targetRow:
      newMatrix.append(matrix[i,:])
    else:
      newMatrix.append(newRow)
  return np.array(newMatrix)

In [ ]:
addRows(M,0,1,2)

array([[22, 29, 25, 30],
       [ 8,  7, 12, 14],
       [ 2,  7,  8, 10]])

In [ ]:
def changeToLeadingOne(matrix,row,column):
  newMatrix =[]
  for i in range(len(matrix)):
    if i != row:
      newMatrix.append(matrix[i,:])
    else:
      newMatrix.append(1/matrix[row,column]*matrix[row,:])
  return np.array(newMatrix)


In [ ]:
changeToLeadingOne(M,3,1)

array([[ 6, 15,  1,  2],
       [ 8,  7, 12, 14],
       [ 2,  7,  8, 10]])

In [ ]:
def findLargestPivot(matrix, column):
  vec = matrix[column:,column]
  vec = np.abs(vec)
  row = np.where(vec == max(vec))
  return row[0][0]+column

In [ ]:
np.abs(A)
def gaussJordan(matrix):
  newMatrix = matrix
  for pivot in range(len(matrix)):
    newpivot = findLargestPivot(newMatrix,pivot)
    newMatrix = swapRows(newMatrix,newpivot,pivot)
    newMatrix = changeToLeadingOne(newMatrix,pivot,pivot)
    for column in range(0,pivot):
      newMatrix = addRows(newMatrix,column,pivot,-newMatrix[column,pivot])
    for column in range(pivot+1,len(matrix)):
      newMatrix = addRows(newMatrix,column,pivot,-newMatrix[column,pivot])
  return newMatrix

In [ ]:
gaussJordan(A)

array([[ 1.        ,  0.        ,  0.        , -0.12672176],
       [ 0.        ,  1.        ,  0.        ,  0.1046832 ],
       [ 0.        ,  0.        ,  1.        ,  1.19008264]])

Support function to sscale rows

In [ ]:
def scale_row(A,k,i):
    "Multiply row i by k in matrix A."
    n = A.shape[0]
    E = np.eye(n)
    E[i,i] = k
    return E @ A

This function is designed to solve a system of at least three equations and three unknowns. 

In [ ]:
def gaussElimination(M):
  M1 = scale_row(M,1/6,0)
  M2 = addRows(M1,1,0,-8)
  M3 = addRows(M2,2,0,-2)
  M4 = scale_row(M3,-1/13,1)
  M5 = addRows(M4,2,1,-2)
  M6 = scale_row(M5,1/M5[2,2],2)
  M7 = addRows(M6,1,2,-M6[1,2])
  M8 = addRows(M7,0,2,-M7[0,2])
  M9 = addRows(M8,0,1,-M8[0,1])
  
  x = M9[:,3].reshape(3,1)

  return x

In [ ]:
gaussElimination(M)

array([[-0.12672176],
       [ 0.1046832 ],
       [ 1.19008264]])

The algorithm created is for handling systems of linear equations that have at least three equations and three unknowns within them. As such the add row, switch row, and multiply by constant functions all work with matrices larger than three by three. This makes it impossible to solve linear equations with less than the set limit. Larger systems of linear equations require larger operations not needed in smaller linear equation systems. Furthermore, the algorithm does not work with singular matrices that cannot be inverted. The solution largely relies on the use of the inverse of the matrix to find a solution.